/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jarhc.gradle;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class JarhcGradlePluginFunctionalTest {

	@TempDir
	File projectDir;

	private File getBuildFile() {
		return new File(projectDir, "build.gradle");
	}

	private File getSettingsFile() {
		return new File(projectDir, "settings.gradle");
	}

	@Test
	void canRunTask() throws IOException {

		// prepare
		writeString(getSettingsFile(), "");
		writeString(getBuildFile(),
				"plugins {" +
						"  id('org.jarhc')" +
						"}");

		// test
		GradleRunner runner = GradleRunner.create();
		runner.forwardOutput();
		runner.withPluginClasspath();
		runner.withArguments("jarhcReport");
		runner.withProjectDir(projectDir);
		BuildResult result = runner.build();

		// assert
		assertTrue(result.getOutput().contains("Hello from plugin 'org.jarhc'"));
	}

	private void writeString(File file, String string) throws IOException {
		try (Writer writer = new FileWriter(file)) {
			writer.write(string);
		}
	}

}
