/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jarhc.gradle;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class JarhcGradlePlugin implements Plugin<Project> {

	public void apply(Project project) {

		// register jarhcReport task
		project.getTasks().register("jarhcReport", task -> {
			task.doLast(s -> System.out.println("Hello from plugin 'org.jarhc'"));
		});

	}

}
