/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jarhc.gradle;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

class JarhcGradlePluginTest {

	@Test
	void apply() {

		// prepare
		Project project = ProjectBuilder.builder().build();

		// test
		project.getPlugins().apply("org.jarhc");

		// assert
		assertNotNull(project.getTasks().findByName("jarhcReport"));
	}

}
