name: Dependency Submission

on:
  push:

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
